"""
Configuration file for the Animal Detection project.
"""
import os

# Model configuration
MODEL_NAME = "resnet18"
CONFIDENCE_THRESHOLD = 0.7

# Dataset configuration
DATASET_PATH = os.path.join(os.path.dirname(__file__), "data")
MODEL_PATH = os.path.join(os.path.dirname(__file__), "models")

# Animal classes (90 different animals from the dataset)
ANIMAL_CLASSES = [
    'antelope', 'bat', 'beaver', 'bee', 'bison', 'boar', 'buffalo', 'butterfly', 'cat', 'caterpillar',
    'chimpanzee', 'cockroach', 'cow', 'coyote', 'crab', 'crocodile', 'deer', 'dog', 'dolphin', 'donkey',
    'dragonfly', 'duck', 'eagle', 'elephant', 'flamingo', 'fly', 'fox', 'goat', 'goldfish', 'goose',
    'gorilla', 'grasshopper', 'hamster', 'hare', 'hedgehog', 'hippopotamus', 'hornbill', 'horse', 'hummingbird', 'hyena',
    'jellyfish', 'kangaroo', 'koala', 'ladybugs', 'leopard', 'lion', 'lizard', 'lobster', 'mosquito', 'moth',
    'mouse', 'octopus', 'okapi', 'orangutan', 'otter', 'owl', 'ox', 'oyster', 'panda', 'parrot',
    'pelecaniformes', 'pelican', 'pig', 'pigeon', 'porcupine', 'possum', 'prawn', 'pufferfish', 'rabbit', 'raccoon',
    'rat', 'rhinoceros', 'sandpiper', 'seahorse', 'seal', 'shark', 'sheep', 'snake', 'sparrow', 'squid',
    'squirrel', 'starfish', 'swan', 'tiger', 'turkey', 'turtle', 'whale', 'woodpecker', 'worm', 'zebra'
]

# Animal features database
ANIMAL_FEATURES = {
    'antelope': 'Antelopes are herbivorous mammals known for their speed and agility.',
    'bat': 'Bats are the only mammals capable of sustained flight.',
    'beaver': 'Beavers are large rodents known for building dams and lodges.',
    'bee': 'Bees are flying insects closely related to wasps and ants.',
    'bison': 'Bison are large, even-toed ungulates in the genus Bison.',
    'boar': 'Boars are wild pigs with thick fur and curved tusks.',
    'buffalo': 'Buffalo are large bovines that are often confused with bison.',
    'butterfly': 'Butterflies are insects with large, colorful wings.',
    'cat': 'Cats are small carnivorous mammals with retractable claws.',
    'caterpillar': 'Caterpillars are the larval stage of butterflies and moths.',
    'chimpanzee': 'Chimpanzees are our closest living relatives in the animal kingdom.',
    'cockroach': 'Cockroaches are insects that can survive in many environments.',
    'cow': 'Cows are domesticated mammals raised for milk and meat.',
    'coyote': 'Coyotes are wild canines native to North America.',
    'crab': 'Crabs are crustaceans with thick exoskeletons and jointed limbs.',
    'crocodile': 'Crocodiles are large aquatic reptiles with powerful jaws.',
    'deer': 'Deer are hoofed mammals with antlers (in males).',
    'dog': 'Dogs are domesticated canines and loyal companions to humans.',
    'dolphin': 'Dolphins are intelligent marine mammals known for their playful nature.',
    'donkey': 'Donkeys are domesticated hoofed mammals related to horses.',
    'dragonfly': 'Dragonflies are predatory insects with two pairs of transparent wings.',
    'duck': 'Ducks are waterfowl with webbed feet and waterproof feathers.',
    'eagle': 'Eagles are large birds of prey with keen eyesight.',
    'elephant': 'Elephants are the largest land animals with distinctive trunks.',
    'flamingo': 'Flamingos are wading birds with distinctive pink coloration.',
    'fly': 'Flies are insects with a single pair of wings.',
    'fox': 'Foxes are small to medium-sized canines known for their cunning.',
    'goat': 'Goats are domesticated mammals often kept for milk and meat.',
    'goldfish': 'Goldfish are popular aquarium fish with bright colors.',
    'goose': 'Geese are waterfowl known for their honking calls.',
    'gorilla': 'Gorillas are the largest primates and are highly intelligent.',
    'grasshopper': 'Grasshoppers are insects known for their jumping ability.',
    'hamster': 'Hamsters are small rodents often kept as pets.',
    'hare': 'Hares are fast-running mammals similar to rabbits.',
    'hedgehog': 'Hedgehogs are spiny mammals that curl into balls for protection.',
    'hippopotamus': 'Hippopotamuses are large semi-aquatic mammals.',
    'hornbill': 'Hornbills are tropical birds with distinctive casques on their bills.',
    'horse': 'Horses are large domesticated mammals used for riding and work.',
    'hummingbird': 'Hummingbirds are tiny birds capable of hovering flight.',
    'hyena': 'Hyenas are African carnivores known for their laugh-like calls.',
    'jellyfish': 'Jellyfish are free-swimming marine animals with gelatinous bodies.',
    'kangaroo': 'Kangaroos are marsupials that hop on their hind legs.',
    'koala': 'Koalas are arboreal marsupials native to Australia.',
    'ladybugs': 'Ladybugs are small beetles often red with black spots.',
    'leopard': 'Leopards are big cats known for their spotted coats.',
    'lion': 'Lions are large cats and are known as the "king of the jungle".',
    'lizard': 'Lizards are reptiles with four legs and scaly skin.',
    'lobster': 'Lobsters are large marine crustaceans with claws.',
    'mosquito': 'Mosquitoes are flying insects that feed on blood.',
    'moth': 'Moths are nocturnal insects related to butterflies.',
    'mouse': 'Mice are small rodents often found near human habitation.',
    'octopus': 'Octopuses are cephalopods with eight arms and intelligence.',
    'okapi': 'Okapis are giraffe relatives with striped legs.',
    'orangutan': 'Orangutans are great apes native to Indonesia and Malaysia.',
    'otter': 'Otters are aquatic mammals known for their playfulness.',
    'owl': 'Owls are nocturnal birds of prey with excellent hearing.',
    'ox': 'Oxen are castrated male cattle used for draft work.',
    'oyster': 'Oysters are marine mollusks with rough shells.',
    'panda': 'Pandas are bears native to China, known for eating bamboo.',
    'parrot': 'Parrots are colorful birds known for their ability to mimic speech.',
    'pelecaniformes': 'Pelecaniformes are an order of aquatic birds including pelicans.',
    'pelican': 'Pelicans are large water birds with distinctive pouches.',
    'pig': 'Pigs are domesticated mammals raised for pork.',
    'pigeon': 'Pigeons are common urban birds often called rock doves.',
    'porcupine': 'Porcupines are rodents covered in sharp quills.',
    'possum': 'Possums are marsupials native to Australia and North America.',
    'prawn': 'Prawns are similar to shrimp but larger.',
    'pufferfish': 'Pufferfish inflate themselves when threatened.',
    'rabbit': 'Rabbits are small mammals with long ears and fluffy tails.',
    'raccoon': 'Raccoons are nocturnal mammals with distinctive masked faces.',
    'rat': 'Rats are medium-sized rodents often considered pests.',
    'rhinoceros': 'Rhinoceroses are large mammals with one or two horns.',
    'sandpiper': 'Sandpipers are shorebirds that wade in shallow water.',
    'seahorse': 'Seahorses are small marine fish with horse-like heads.',
    'seal': 'Seals are marine mammals that spend time both in water and on land.',
    'shark': 'Sharks are large predatory fish with cartilaginous skeletons.',
    'sheep': 'Sheep are domesticated mammals raised for wool and meat.',
    'snake': 'Snakes are limbless reptiles with elongated bodies.',
    'sparrow': 'Sparrows are small passerine birds commonly found in cities.',
    'squid': 'Squids are cephalopods with ten arms and streamlined bodies.',
    'squirrel': 'Squirrels are small rodents that store nuts for winter.',
    'starfish': 'Starfish are marine animals with star-shaped bodies.',
    'swan': 'Swans are large water birds with long necks.',
    'tiger': 'Tigers are the largest cats and are known for their stripes.',
    'turkey': 'Turkeys are large birds native to North America.',
    'turtle': 'Turtles are reptiles with protective shells.',
    'whale': 'Whales are large marine mammals that breathe air.',
    'woodpecker': 'Woodpeckers are birds that drill holes in trees for food.',
    'worm': 'Worms are invertebrates with elongated soft bodies.',
    'zebra': 'Zebras are horses with distinctive black and white stripes.'
}