artifact_location: file:D:/Project/Animal_Detection/yolo_classification_dataset/runs/mlflow/0
creation_time: 1759000766795
experiment_id: '0'
last_update_time: 1759000766795
lifecycle_stage: active
name: Default
